# Generated by Django 5.2.6 on 2025-09-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_last_stock_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_thumbnail_large',
            field=models.ImageField(blank=True, help_text='Large thumbnail (600x600)', null=True, upload_to='products/%Y/%m/%d/thumbnails'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumbnail_medium',
            field=models.ImageField(blank=True, help_text='Medium thumbnail (300x300)', null=True, upload_to='products/%Y/%m/%d/thumbnails'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumbnail_small',
            field=models.ImageField(blank=True, help_text='Small thumbnail (100x100)', null=True, upload_to='products/%Y/%m/%d/thumbnails'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
